import pygame as pg

pg.init()

# SCREEN SETTINGS
SIZE = (WIDTH, HEIGHT) = (1280, 720)
FPS = 60
TILESIZE = 32
SLOTSIZE = TILESIZE * 2
INVENTORY_SIZE = 5
# physics
GRAVITY = 0.1
TERMINAL_VELOCITY = 2
PLAYER_SPEED = 5
PLAYER_JUMP_POWER = 10
TERRAIN_VOLATILITY = 0.08
ENEMY_AGGRO_RANGE = 17.5